name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "0 0 * * *"
permissions:
  contents: write
  pull-requests: write
  security-events: write
  # [Mandatory If using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  id-token: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["main"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Frogbot Scan
        uses: jfrog/frogbot@v2
        continue-on-error: true  # Continue even if Frogbot fails due to false positives

        env:
          JF_URL: https://rodolphefplus.jfrog.io 
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_DEPS_REPO: soleng-dev-nuget
          JF_PROJECT: "sai"
          JF_WORKING_DIR: "."

        with:
          oidc-provider-name: rodolphef-nuget-webui
          oidc-audience: rodolphef-lollms-nuget-audience

      - name: Check Frogbot Exit Code
        if: failure()
        run: |
          echo "Frogbot scan completed with warnings/errors, but continuing..."
          echo "This may be due to false positives in dependency scanning."
          echo "Please review the scan results manually."

